#!/usr/bin/env zsh

# The goal of this script is to copy all dotfiles.

# Get directory in which this script resides.
script_dir="$( cd $( dirname "${BASH_SOURCE[0]}" ) &> /dev/null && pwd )"

# Init variables
dry_run="0"

# Parse arguments
while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

log "---------- setup_dev -> dev-env ----------"
log "script_dir=$script_dir"


