#!/usr/bin/env bash

# The goal of this script is to execute all scripts in runs/

# Get directory in which this script resides.
script_dir="$( cd $( dirname "${BASH_SOURCE[0]}" ) &> /dev/null && pwd )"

# Init variables
filter=""
dry_run="0"

# Parse arguments
while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

log "script_dir=$script_dir"
log "------ setup_dev -> essentials -------"
execute $script_dir/essentials/git

log "---------- setup_dev -> run ----------"
log "env: $env -- filter: $filter"

# Get all scripts (executable files) in directory ./runs/
scripts=`find $script_dir/runs -maxdepth 1 -mindepth 1 -executable -type f`

# Execute each script
log "Searching for scripts in runs/"

for script in $scripts; do
    # script does not contain filter
    if echo "$script" | grep -qv "$filter"; then
        log "grep \"$filter\" filtered out $script"
        continue
    fi

    execute $script

done

