#!/usr/bin/env zsh

echo "Starting setup_dev -> run"

# Get directory in which this script resides.
script_dir="$( cd $( dirname "${BASH_SOURCE[0]}" ) &> /dev/null && pwd )"
echo "script_dir=$script_dir"

# Get first argument
filter="$1"
echo "filter=$filter"

