# Use headless Ubuntu/Xfce containers with VNC
# https://github.com/accetto/ubuntu-vnc-xfce-g3
FROM accetto/ubuntu-vnc-xfce-g3
# You should be able to connect to port 5901 with a VNC viewer with password: headless
